artifact_uri: file:C:\Users\ngaleano_tredasoluti\Documents\GitHub\PRE-08-mlflow-tracking-local-NatalyGaleano\my_mlruns/677167288525922540/2ffbf642fcdc41fdba1a573388abfb74/artifacts
end_time: 1748100717228
entry_point_name: ''
experiment_id: '677167288525922540'
lifecycle_stage: active
run_id: 2ffbf642fcdc41fdba1a573388abfb74
run_name: elasticnet_566cf2d9
run_uuid: 2ffbf642fcdc41fdba1a573388abfb74
source_name: ''
source_type: 4
source_version: ''
start_time: 1748100717087
status: 3
tags: []
user_id: ngaleano_tredasoluti
